version: "3.8"

services:
  # MongoDB 8 with a named volume for persistence
  mongo:
    image: mongo:8
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Redis (v6) with a named volume
  redis:
    image: redis:6
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # RabbitMQ with management UI
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  # Nginx reverse-proxy (paths in nginx/nginx.conf)
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  # API Gateway
  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - rabbitmq
      - nginx
    env_file:
      - ./.env
    ports:
      - "3000:3000"

  # User Service
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - rabbitmq
    env_file:
      - ./services/user-service/.env
    ports:
      - "3001:3000"
    # Mount your Firebase service account key into the container
    volumes:
      - ./services/user-service/secrets/zefy-30706-c8da4feed63f.json:/secrets/zefy-30706-c8da4feed63f.json:ro
    # Tell the Admin SDK where to find it
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/zefy-30706-c8da4feed63f.json
  aggregator-service:
    build:
      context: .
      dockerfile: services/aggregator-service/Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - rabbitmq
    env_file:
      - ./services/aggregator-service/.env
    ports:
      - "3002:3000"
  parcel-service:
    build:
      context: .
      dockerfile: services/parcel-service/Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
      - rabbitmq
    env_file:
      - ./services/parcel-service/.env
    ports:
      - "3003:3000"
volumes:
  mongo-data:
  redis-data:
  rabbitmq-data:
