module.exports = {
  apps: [
    {
      name: 'user-service',
      script: 'services/user-service/dist/index.js',
      cwd: '/home/ubuntu/zefy-home-services-backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        MONGO_URI: 'mongodb://localhost:27017/zefy_users',
        REDIS_URL: 'redis://localhost:6379',
        AMQP_URL: 'amqp://admin:password123@localhost:5672',
        DLT_BASE_URL: 'https://www.fast2sms.com/dev/bulkV2',
        FAST2SMS_API_KEY: 'ET3lJmIMgdqFcZa0rBkvHGsDOUtK9Lif7Ne5u2xAwhbXYP8p14TxmGajIR8OfVvJnotHdrhpgMXw9LA7',
        DLT_ROUTE: 'dlt',
        DLT_SENDER_ID: 'ZEFY',
        DLT_OTP_MESSAGE_ID: '198600'
      },
    },
    {
      name: 'booking-service',
      script: 'services/booking-service/dist/index.js',
      cwd: '/home/ubuntu/zefy-home-services-backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
        MONGO_URI: 'mongodb://localhost:27017/zefy_bookings',
        REDIS_URL: 'redis://localhost:6379',
        AMQP_URL: 'amqp://admin:password123@localhost:5672',
        USER_SERVICE_URL: 'http://localhost:3001',
        PARTNER_SERVICE_URL: 'http://localhost:3003',
        RAZORPAY_KEY_ID_TEST: 'rzp_test_KQ4vZMSPLvhaYq',
        RAZORPAY_KEY_SECRET_TEST: '9JGvYZAAljCx6ZTTs08WBXa4',
        RAZORPAY_KEY_ID: 'rzp_live_RHWDkFOgJTOPnl',
        RAZORPAY_KEY_SECRET: 'TlxWmyZTgwD062iomPHflH6r'
      },
    },
    {
      name: 'partner-service',
      script: 'services/partner-service/dist/index.js',
      cwd: '/home/ubuntu/zefy-home-services-backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
        MONGO_URI: 'mongodb://localhost:27017/zefy_partners',
        REDIS_URL: 'redis://localhost:6379',
        AMQP_URL: 'amqp://admin:password123@localhost:5672',
        BOOKING_SERVICE_URL: 'http://localhost:3002',
        AWS_ACCESS_KEY_ID: "AKIAU6GD3YQG6AVWBJG4",
        AWS_SECRET_ACCESS_KEY: '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',
        AWS_REGION: 'ap-south-1',
        AWS_S3_BUCKET: "zefy"
      },
    },
    {
      name: 'gateway',
      script: 'services/gateway/dist/index.js',
      cwd: '/home/ubuntu/zefy-home-services-backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        USER_SERVICE_URL: 'http://localhost:3001',
        BOOKING_SERVICE_URL: 'http://localhost:3002',
        PARTNER_SERVICE_URL: 'http://localhost:3003',
        REDIS_URL: 'redis://localhost:6379',
        AMQP_URL: 'amqp://admin:password123@localhost:5672'
      },
    },
    {
      name: 'admin',
      script: 'services/admin-service/dist/index.js',
      cwd: '/home/ubuntu/zefy-home-services-backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
        MONGO_URI: 'mongodb://localhost:27017/zefy_admin',
        REDIS_URL: 'redis://localhost:6379',
        AMQP_URL: 'amqp://admin:password123@localhost:5672',
      },
    }
  ]
};
